HW15/shopper/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'search', to: 'search#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'

  # Defines the cart path route
  get 'cart', to: 'carts#show', as: :cart
  resources :line_items, only: %i[create destroy update]
  # post 'line_items/:id/increase_quantity', to: 'line_items#increase_quantity', as: 'line_item_increase'
  # post 'line_items/:id/decrease_quantity', to: 'line_items#decrease_quantity', as: 'line_item_decrease'
  resources :orders, only: %i[index create show destroy]
  patch 'orders/:id/update', to: 'orders#update', as: 'order_paid'
end

HW15/shopper/app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :bigint           not null, primary key
#  status     :integer          default("unpaid"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cart_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_orders_on_cart_id  (cart_id)
#  index_orders_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (cart_id => carts.id)
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :user

  enum :status, %i[unpaid paid]
end

HW15/shopper/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[show update destroy]

  def index
    @orders = current_user.orders
  end

  def create
    @order = current_user.orders.create(cart: current_cart)

    cookies.delete(:cart_id)
    redirect_to order_path(@order), notice: 'Order was created successfully'
  end

  def show
    @line_items = @order.cart.line_items
  end

  def update
    @order.paid!
    cookies.delete(:cart_id)
    OrderMailer.with(user: current_user, order: @order).new_order_email.deliver_now

    redirect_to order_path(@order), notice: 'Order was paid successfully'
  end

  def destroy
    @order.destroy
    redirect_to orders_path, notice: "Order #{@order.id} deleted from cart"
  end

  private

  def set_order
    @order = current_user.orders.find(params[:id])
  end
end

HW15/shopper/app/views/orders/index.html.erb
<% if current_user %>
  <div class="container text-center">
    <h3>Your Orders</h3>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <table class='table table-hover'>
        <thead>
          <tr>
            <th>#</th>
            <th>Status</th>
            <th>Price</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
          <td><%= order.id %></td>
          <td><%= order.status %></td>
          <td><%= number_to_currency order.cart.total_price %></td>
          <td>
            <div class="row">
            <div class="col">
                <%= link_to "Show", order_path(order), class: "btn btn-outline-secondary" %>
              </div>
              <div class="col">
                <%= button_to "Delete", order_path(order), method: :delete, class: "btn btn-outline-secondary" %>
              </div>
            </div>
          </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
<% else %>
    <h3>You don't have any orders </h3>
  </div>
<% end %>

HW15/shopper/app/views/orders/show.html.erb
<% if current_user %>
<div class="container text-center">
  <h3>Your Order</h3>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <table class="table table-hover">
    <thead>
      <tr>
        <th></th>
        <th scope="col">Image</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
    <% @line_items.each.with_index do |line_item, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <th> 
          <% if line_item.product.image.attached? %>
            <%= image_tag line_item.product.image, height: 80, height: 80 %>
            <% else %>
            <%= image_tag("no_image_item.jpeg", height: 80, height: 80) %>
          <% end %>
        </th>
        <td><%= line_item.product.name %></td>
        <td>
        <div class="container">
          <div class="row row-cols-2 row-cols-lg-3">
            <div class="col">
              <%= line_item.quantity %>
            </div>
          </div>
        </div>
        </td>
        <td><%= number_to_currency(line_item.total_price) %></td>
      </tr>
      <% end %>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>Total price: <%= number_to_currency @order.cart.total_price %></td>
    </tbody>
    </table>
  </div>
  <% if @order.paid? %>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <h4>Paid</h4>
    </div>
  <% else %>
    <%= button_to 'Proceed to payment', order_paid_path, method: :patch, class: "btn btn-primary btn-lg" %>
  <% end %>
</div>
<% end %>