HW15/shopper/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'search', to: 'search#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'

  # Defines the cart path route
  get 'cart', to: 'carts#show', as: :cart
  resources :line_items, only: %i[create destroy update]
  # post 'line_items/:id/increase_quantity', to: 'line_items#increase_quantity', as: 'line_item_increase'
  # post 'line_items/:id/decrease_quantity', to: 'line_items#decrease_quantity', as: 'line_item_decrease'
  resources :orders, only: %i[index create show destroy]
  patch 'orders/:id/update', to: 'orders#update', as: 'order_paid'
end

HW15/shopper/app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_one :order, dependent: :destroy

  def add_product(product)
    line_items.create(product:, quantity: 1)
  end

  def total_price
    line_items.includes(:product).sum(&:total_price)
  end
end

HW15/shopper/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_cart.line_items
  end
end

HW15/shopper/app/views/carts/_line_item_counter.html.erb
    <%= current_cart.line_items.includes(:product).sum(:quantity) if current_cart.line_items.exists? %>
    

HW15/shopper/app/views/carts/show.html.erb
<% if current_user %> 
  <% if @line_items.exists? %>
    <div class="container text-center">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <table class="table table-hover">
          </thead>
            <tr>
              <th scope="col">Image</th>
              <th scope="col">Name</th>
              <th scope="col">Quantity</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
          <% @line_items.includes(:product).each do |line_item| %>
            <tr>
              <th scope="row">
                <% if line_item.product.image.attached? %>
                  <%= image_tag line_item.product.image, height: 80, height: 80 %>
                  <% else %>
                  <%= image_tag("no_image_item.jpeg", height: 80, height: 80) %>
                <% end %>
              </th>
              <td><%= line_item.product.name %></td>
              <td>
              <div class="container">
                <div class="row row-cols-2 row-cols-lg-3">
                  <div class="col">
                    <%= line_item.quantity %>
                  </div>
                  <div class="col-4 col-lg-2">
                    <%= button_to "-", line_item_path(line_item), params: { quantity: 'decrease' }, method: :patch, class: "btn btn-outline-secondary" %>
                  </div>
                  <div class="col-4 col-lg-2">
                  <%= button_to "+", line_item_path(line_item), params: { quantity: 'increase'}, method: :patch, class: "btn btn-outline-secondary" %>
                  </div>
                  <div class="col">
                  <%= button_to "delete", line_item_path(line_item), method: :delete, class: "btn btn-outline-secondary" %>
                  </div>
                </div>
              </div>
              </td>
              <td><%= number_to_currency line_item.total_price%></td>
            </tr>
            <% end %>
            <td></td>
            <td></td>
            <td></td>
            <td>Total price: <%= number_to_currency current_cart.total_price %></td>
          </tbody>
        </table>
      </div>
      <div>
      <%= button_to 'Checkout', orders_path, class: "btn btn-primary btn-lg"%>
      </div>
    </div>
  <% else %>
    <h1>Currently no items in the cart</h1>
  <% end %>
<% end %>