HW11/shopper/config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'

  # Defines the cart path route
  get 'cart', to: 'carts#show', as: :cart
  resources :line_items, only: %i[create destroy]
  post 'line_items/:id/increase_quantity', to: 'line_items#increase_quantity', as: 'line_item_increase'
  post 'line_items/:id/decrease_quantity', to: 'line_items#decrease_quantity', as: 'line_item_decrease'
  resources :orders, only: %i[index create show destroy]
  patch 'orders/:id/update_status', to: 'orders#update_status', as: 'order_paid'

  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'
end

HW11/shopper/app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!

  def show
    current_user.set_payment_processor :stripe
    current_user.payment_processor.customer

    @checkout_session = current_user
                        .payment_processor
                        .checkout(
                          mode: 'payment',
                          line_items: 'price_1MP0IFHALZtoIW7LhgMPpa7L',
                          success_url: checkout_success_url
                        )
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @line_items = Stripe::Checkout::Session.list_line_items(params[:session_id])
  end
end

HW11/shopper/app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

HW11/shopper/app/views/checkouts/show.html.erb
<h1>checkout</h1>

<%= render partial: 'pay/stripe/checkout_button', locals: {
  session: @checkout_session,
  title: 'Checkout'
} %>

HW11/shopper/app/views/checkouts/success.html.erb
<h1>Success!</h1>
<h2>Your total was $<%= @session.amount_total.to_f / 100 %>
  <br />
  <%= @line_items.each do |item| %>
    <h3><%= item.description %></h3>
    <% end %>

HW11/shopper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidebar'%>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
  </body>
</html>

HW11/shopper/app/views/products/show.html.erb
<div class="container col-xxl-8 px-4 py-5">
  <div class="row flex-lg-row-reverse align-items-center g-5">
    <div style="margin:0" class="col-lg-6 mg-0">
      <h1 class="display-5 fw-bold lh-1 mb-3"><%= @product.name %></h1>
      <p class="lead"><%= @product.description %></p>
      <h6 class="lead">Categories:</h6>
      <% @product.categories.each do |category|%>
      <h6 class="lead"> <%= category.title %></h6>
      <% end %>
      <p class="lead"><%= number_to_currency(@product.price) %></p>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <%if user_signed_in? %>
            <%= link_to 'Buy', checkout_path, class:"btn btn-primary btn-lg px-4 me-md-2" %>
            <%= button_to 'Add to cart', line_items_path(product_id: @product.id), class:"btn btn-outline-secondary btn-lg px-4" %>
          <% else %>
            <%=  link_to new_user_session_path do %>
            <button type="button" class="btn btn-primary btn-lg px-4 me-md-2">Buy</button>
            <button type="button" class="btn btn-outline-secondary btn-lg px-4">Add to cart</button>
            <% end %>
        <% end %>
      </div>
    </div>
    <div style="margin:0" class="col-10 col-sm-8 col-lg-6">
      <img class="bd-placeholder-img card-img-top" width="100%" height="225" src=<%= @product.image %> class="card-img-top" alt=<%= @product.name %>>
    </div>
  </div>
</div>