HW15/shopper/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'search', to: 'search#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'

  # Defines the cart path route
  get 'cart', to: 'carts#show', as: :cart
  resources :line_items, only: %i[create destroy update]
  # post 'line_items/:id/increase_quantity', to: 'line_items#increase_quantity', as: 'line_item_increase'
  # post 'line_items/:id/decrease_quantity', to: 'line_items#decrease_quantity', as: 'line_item_decrease'
  resources :orders, only: %i[index create show destroy]
  patch 'orders/:id/update', to: 'orders#update', as: 'order_paid'
end

HW15/shopper/app/views/layouts/_flash_message.html.erb
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

HW15/shopper/app/views/layouts/_header.html.erb
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <%= link_to root_path do %>
          <%= image_tag('logo.png', width: '150px') %>
          <% end %>
        </div>
      </div>

      <div class="col-5">
        <%= render 'search/form' %>
      </div>

      <div class="col">
        <div class="text-end">
          <% if user_signed_in? %>
            <div class="dropdown-center">
              <button class="btn btn-outline-light me-2 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Profile
              </button>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li>
                  <%# turbo_frame_tag "items_count" do %>
                   <%= link_to "Cart (#{render 'carts/line_item_counter'})", cart_path, class: "dropdown-item" %>
                  <%# end %>
                </li>
                <li>
                  <%= link_to "Orders", orders_path, class: "dropdown-item" %>
                </li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
                </li>
              </ul>
            </div>
            <% else %>
            <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-light me-2" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

HW15/shopper/app/views/layouts/_sidebar.html.erb
<div class="b-example-divider b-example-vr overflow-auto position-relative"></div>
  <div style="float:left;width:250px" class="flex-shrink-0 p-3 bg-white position-relative">
      <span class="fs-5 fw-semibold d-flex items-center">Filter</span>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Categories
        </button>
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <% Category.all.each do |category| %>
              <li class="nav-item"> 
                <%=link_to category.title, category, class: "link-dark d-inline-flex text-decoration-none rounded" %>
              </li>
            <% end %>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</div>

HW15/shopper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidebar'%>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
  </body>
</html>